Home page 1.0
GCUCoders/Tech-Club-Site pull request #18
Opened 2021-11-02 02:06 UTC by typhlosion64

## Summary of Changes
- i created 2 divs with grid
- one for quotes the other for buttons and stuff

## Imagery
None

## Additional Notes

2021-11-02 02:49 UTC, GCUCoding submitted a review, later dismissed
- Please make sure that all pictures are placed in the preexisting "images" folder, not a new pics folder.
- Please remove patrick.jpg. Unfortunately now that the repo is public we need to maintain a professional image *(I know I know I'm a buzzkill)*

2021-11-19 01:41 UTC, elijaholmos requested changes
JS changes; prefer `let` and `const` over `var`
otherwise LGTM

2021-11-19 01:41 UTC, elijaholmos commented on js/home.js
> +var p3 = "Hardware is doing something.";
```suggestion
const cyber = "Cyber Security";
const webdev = "Web Development";
const embedded = "Embedded Development";
const hardware = "Hardware";

const p0 = "Cyber Security is doing things.";
const p1 = "Web Dev is doing things.";
const p2 = "Embedded Dev is doing something.";
const p3 = "Hardware is doing something.";
```

2021-11-19 01:41 UTC, elijaholmos commented on js/home.js
> +var speed = 40; /* The speed/duration of the effect in milliseconds */
```suggestion
let i = 0;
const txt =
  "Welcome to the GCU Technology Club's Official Web Site!"; /* The text */
const speed = 40; /* The speed/duration of the effect in milliseconds */
```

2021-11-19 01:41 UTC, elijaholmos commented on js/home.js
> +var y = 0;
```suggestion
let  y = 0;
```

2021-11-19 21:10 UTC, elijaholmos approved these changes
nice job with the changes!

2021-11-19 21:14 UTC, merged