projects link
GCUCoders/Tech-Club-Site pull request #50
Opened 2021-11-30 01:18 UTC by 21Danson

## Summary of Changes

first turn in of projects website link

## Imagery

used temporary pictures to depict what future projects will look like on slider

## Additional Notes

2021-11-30 01:26 UTC, GCUCoding reviewed
Fixed a couple of issues that GitHub created, will look into it more later. Great job so far!

2021-11-30 01:32 UTC, elijaholmos requested changes
Added some JS changes

2021-11-30 01:32 UTC, elijaholmos commented on projects.html
> +var slideIndex = 0;
```suggestion
let slideIndex = 0;
```

2021-11-30 01:32 UTC, elijaholmos commented on projects.html
> +  var dots = document.getElementsByClassName("dot");
```suggestion
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
```

2021-11-30 01:32 UTC, elijaholmos commented on projects.html
> +  }
```suggestion
  for (const slide of slides) {
    slide.style.display = "none";  
  }
```

2021-11-30 01:32 UTC, elijaholmos commented on projects.html
> +  if (slideIndex > slides.length) {slideIndex = 1}
```suggestion
  if (slideIndex > slides.length) slideIndex = 1;
```

2021-11-30 01:32 UTC, elijaholmos commented on projects.html
> +  dots[slideIndex-1].className += " active";
We can actually use DOM `classList` property here:
```suggestion
  for (const dot of dots) {
    dot.classList.remove('active');
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].classList.add('active');
  ```

2021-12-10 01:15 UTC, elijaholmos approved these changes

2021-12-10 01:15 UTC, merged